export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const PROVIDER_LOGIN_SUCCESS = "PROVIDER_LOGIN_SUCCESS";
export const PROVIDER_LOGIN_ERROR = "PROVIDER_LOGIN_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOAD_ERROR = "USER_LOAD_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const LOGOUT = "LOGOUT";

// USER ACTIONS
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const GET_CODEWARS_PROFILE = "GET_CODEWARS_PROFILE";
export const GET_CODEWARS_PROFILE_ERROR = "GET_CODEWARS_PROFILE_ERROR";
export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE";
export const GET_CURRENT_PROFILE_ERROR = "GET_CURRENT_PROFILE_ERROR";
export const IS_ANALYSIS_READY = "IS_ANALYSIS_READY";
export const IS_ANALYSIS_READY_ERROR = "IS_ANALYSIS_READY_ERROR";
