export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const PROVIDER_REGISTER_SUCCESS = "PROVIDER_REGISTER_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOAD_ERROR = "  USER_LOAD_ERROR";

// USER ACTIONS
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
